### ISSUE TITLE
f-ing drake doesn't like `read.csv()`?

### ISSUE THREAD

**Issue by kaizadp** [kaizadp/destabilization_som#3]
@bpbond 

My `drake` plan doesn't like reading some csv files. `make()` fails because the file cannot be found. But when I run the script without drake, it works fine. 

This issue isn't consistent across all the `read.csv()` targets though, and I can't figure out why only some targets fail. e.g. in this case, "weoc_traykey not found", but I think it was able to read `irms_weoc_report`.

P.S. I've had this problem before, and I "solve" it by keeping the `read.csv()` commands outside the drake plan. I figure it's time for a real solution now. 
P.P.S. This script is set up so it runs the functions from script `3-irms_processing.R` first and then does the processing. 

https://github.com/kaizadp/destabilization_som/blob/1ae75c317614c166d5a3dbda1cfeada776ba7898/code/3b-irms_plan.R#L26

```
x fail weoc_combined
Error: target weoc_combined failed.
diagnose(weoc_combined)$error$message:
  object 'weoc_traykey' not found
diagnose(weoc_combined)$error$calls:
  global::process_weoc_files(irms_weoc_report, tc_weoc_report)
  irms_weoc_report %>% dplyr::select(name, sample_group, d13C_VPDB) %>% 
    filter(sample_group == "samples") %>% left_join(weoc_traykey, 
    by = "name") %>% filter(!is.na(core)) %>% mutate(R13C = ((d13C_VPDB/1000) + 
    1) * C_VPDB, R13C = round(R13C, 6)) %>% dplyr::select(core, 
    weoc_rep, d13C_VPDB, R13C)
  base::withVisible(eval(quote(`_fseq`(`_lhs`)), env, env))
  base::eval(quote(`_fseq`(`_lhs`)), env, env)
  base::eval(quote(`_fseq`(`_lhs`)), env, env)
  `_fseq`(`_lhs`)
  magrittr::freduce(value, `_function_list`)
  function_list[[i]](value)
  dplyr::left_join(., weoc_traykey, by = "name")
  dplyr:::left_join.data.frame(., weoc_traykey, by = "name")
  dplyr::auto_copy(x, y, copy = copy)
  dplyr::same_src(x, y)
  dplyr:::same_src.data.frame(x, y)
  base::is.data.fram
```

**Comment by bpbond** [comment]
Is this error reproducible by me? If I clone the repo and run `make()` should I hit it?

**Comment by bpbond** [comment]
...if not please provide clear directions to reproduce error if possible. Thanks!

**Comment by kaizadp** [comment]
Yes, you should be able to clone the repo and run this script to get the error. 
Thanks

**Comment by bpbond** [comment]
Hi @kaizadp so the reason it's failing is not obscure. I'm not saying this to make you feel bad, but if you're going to use drake, there are a few concepts we need to make sure you grok fully.

1. The idea of variable scope (a general concept in programming languages) and environments (R specifically). A good short summary of this is [here](https://www.datamentor.io/r-programming/environment-scope/) for example.
2. The precept that the drake package runs workflows—plans—in their own 'clean' environments to avoid crapping up the user's environment (and so nothing the user has done in their own environment affects the plan execution).
3. `drake` targets aren't objects in the environment until you `readd()` them.

Putting these together:
* `process_weoc_files()` included a reference to `weoc_traykey` on line 50, but this isn't defined in `process_weoc_files()`, nor is it a parameter to it.
* So R looks _outside_ the function to try to find this object.
* The `drake` execution environment, the 'enclosing environment' (where it was called from) won't have this defined either. _This is a good thing_: it's not consuming memory unless used, and `drake` really wants you to define all function inputs explicitly (which is good programming practice more generally).
* The result is that R can't find  `weoc_traykey` anywhere, and stops with an error.

The solution? Add `weoc_traykey` to be a parameter to `process_weoc_files()`.

I hope I'm not being snarky above, truly! Just trying to walk you through the logic.

**Comment by bpbond** [comment]
This will apply to other inputs that `process_weoc_files()` needs as well...

**Comment by kaizadp** [comment]
I think I get it. I assumed `drake` would see `weoc_traykey` from the enclosing drake environment because it was a target in the plan. 
I’m still new to `drake` and functions, so this helped! (and didn’t come across as snarky) 
Thanks!

**Comment by bpbond** [comment]
Right, the targets aren't variables in a normal sense. You can either pass them in as parameters to the function, or use `readd()` inside the function to load what you need.

**Comment by kaizadp** [comment]
Works now! Thanks
