### ISSUE TITLE
markdown directories

### ISSUE THREAD

**Issue by kaizadp** [kaizadp/destabilization_som#4]
@bpbond 
I am trying to set up my Markdown files so the .Rmd and .md files are in separate directories (see below). Two reasons: (a) keep all the coding documents in the same directory, and (b) that way the `reports` directory has only the final rendered files, making it easier for non-Markdown users.

```
_
|-- code/
|       |---- irms_report.Rmd
|
|-- reports/
        |---- irms_report.md
```

Problem: the images aren't rendered in the final .md file when I do this. 

---

1. When I set `fig.paths = FIGS` in my .Rmd file, the figures are saved to `code/FIGS/`, and so my .md file cannot access them over in the `reports/` directory. 

2. When I remove `fig.paths = ...`, it saves the figures to `reports/...`, but it renders the .md file with absolute (local) paths for the figures. 

![image](https://user-images.githubusercontent.com/50244730/100783597-d549fd00-33c2-11eb-8313-e840bf62bdf6.png)

---
I set the `output_dir()` here:
https://github.com/kaizadp/destabilization_som/blob/248be676f3b70f9f6d03b328187b9023197cfaa1/code/3b-irms_plan.R#L49-L53

and these are the Markdown files in question:

[irms_report.Rmd](https://github.com/kaizadp/destabilization_som/blob/master/code/irms_report.Rmd)
[irms_report.md](https://github.com/kaizadp/destabilization_som/blob/master/reports/irms_report.md)

Do you know how to fix this issue with figure paths across different directories?
Is it just easier to just leave the .Rmd and .md files in the same `reports` folder?

Thanks!

**Comment by kaizadp** [comment]
Just figured it out, I think: 7ca0069
`ezknitr` does the trick, but the output dimensions, etc. are a little different from classic `knitr`.

**Comment by bpbond** [comment]
Glad you found a solution. The only thing I know is that rmarkdown's directory-handling has caused repeated problems for people (as a google search shows).

**Comment by kaizadp** [comment]
Looks like I spoke too soon. `ezknitr` did what I wanted, but I wasn't able to make any further changes to the output .md file. It appears frozen, and restarting, clearing the cache, etc. didn't work. 
I'm sticking with the conventional "same directory for .Rmd and .md" approach for now.
